### ISSUE TITLE
/path/to/your/imdb_IRMA

### ISSUE THREAD

**Issue by zhaoxuyan** [Xiaoming-Zhao/DDSM-LJPEG#1]
请问imdb_IRMA是什么目录
what is the "imdb_IRMA" directory mean please?

**Comment by zhaoxuyan** [comment]
what is "imdb_IRMA" directory mean?

**Comment by Xiaoming-Zhao** [comment]
IRMA is a database for mammography analysis. You could find the description [here](http://www.mammoimage.org/databases/). However, it seems that the website for IRMA is down now.

**Comment by zhaoxuyan** [comment]
Thank you for your reply
